steps:
  - label: "Pull upstream packages"
    command:
      - "chmod +x download-packages.sh"
      - "chmod +x pack-all-installed.sh"
      - "./download-packages.sh"
      - "./pack-all-installed.sh"
    artifact_paths:
      - "tgz-packages/**/*"
  - wait: ~
  - label: "Push packages to Buildkite registry"
    plugins:
      - publish-to-packages#v2.2.0:
          artifacts: "tgz-packages/**/*"
          registry: "packages-sandbox/is-that-you-nan"

  - label: "Run tests"
    command: 
      - "npm install express async lodash --registry https://packages.buildkite.com/packages-sandbox/is-that-you-nan/npm/ --loglevel verbose"
      - "npm test"
