steps:
  - label: "Pull upstream packages"
    command: "npm install express async lodash --loglevel verbose"
    artifact_paths:
      - "node_modules/**/*"

  - label: "Push packages to Buildkite registry"
    plugins:
      - publish-to-packages#v2.2.0:
          artifacts: "node_modules/**/*"
          registry: "packages-sandbox/monty-python-and-the-holy-grail"
  - wait

  - label: "Run tests"
    command: "npm test"
