steps:
  - label: "Pull upstream packages"
    commands:
      - "chmod +x pack-all-installed.sh"
      - "npm install lodash --loglevel verbose"
      - "./pack-all-installed.sh"
    artifact_paths:
      - "tgz-packages/**/*"
  - wait: ~
  - label: "Push packages to Buildkite registry"
    soft_fail:
    - exit_status: 1
    plugins:
      - publish-to-packages#v2.2.0:
          artifacts: "tgz-packages/**"
          registry: "packages-sandbox/is-that-you-nan"
  - wait: ~
  - label: "Run tests"
    commands: 
      - "npm install lodash --registry https://packages.buildkite.com/packages-sandbox/is-that-you-nan/npm/ --loglevel verbose"
      - "npm list lodash --depth=0"
