steps:
  - label: "Pull upstream packages"
    command: "npm pack express async lodash --loglevel verbose"
    artifact_paths:
      - "*.tgz"
  - wait: ~
  - label: "Push packages to Buildkite registry"
    plugins:
      - publish-to-packages#v2.2.0:
          artifacts: "*.tgz"
          registry: "packages-sandbox/monty-python-and-the-holy-grail"
  - wait: ~

  - label: "Run tests"
    command: "npm test"
