steps:
  - label: "Pull upstream packages"
    command: "npm pack express async lodash --loglevel verbose"
    artifact_paths:
      - "*.tgz"
  - wait: ~
  - label: "Push packages to Buildkite registry"
    plugins:
      - publish-to-packages#v2.2.0:
          artifacts: "*.tgz"
          registry: "packages-sandbox/is-that-you-nan"

  - label: "Run tests"
    command: "npm install express async lodash --registry https://packages.buildkite.com/packages-sandbox/is-that-you-nan/npm/ --loglevel verbose"
    command: "npm test"
